/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.FoodCollectionSupervisor;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kunal
 */
public class ReportsWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ReportsWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;

    public ReportsWorkArea(JPanel userProcessContainer,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBestCitizen = new javax.swing.JButton();
        btnFoodCollectedCitizen = new javax.swing.JButton();
        btnFoodCollectedRestaurqant = new javax.swing.JButton();
        btnMostPopularArea = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Food Collection Admin Reports");

        btnBestCitizen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBestCitizen.setText("Types Of Food Collected in a time Period >>");
        btnBestCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestCitizenActionPerformed(evt);
            }
        });

        btnFoodCollectedCitizen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFoodCollectedCitizen.setText("Types of food collected from all the Citizen >>");
        btnFoodCollectedCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodCollectedCitizenActionPerformed(evt);
            }
        });

        btnFoodCollectedRestaurqant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFoodCollectedRestaurqant.setText("Types of food collected from all the Restaurants >>");
        btnFoodCollectedRestaurqant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodCollectedRestaurqantActionPerformed(evt);
            }
        });

        btnMostPopularArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMostPopularArea.setText("Most popular area of Donation >>");
        btnMostPopularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostPopularAreaActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(299, 299, 299))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnFoodCollectedCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFoodCollectedRestaurqant, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBestCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMostPopularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(209, 209, 209))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(btnBestCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnFoodCollectedCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnFoodCollectedRestaurqant, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnMostPopularArea, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btnback)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBestCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestCitizenActionPerformed
        // TODO add your handling code here:
        TotalFoodDonation manageCityJPanel = new TotalFoodDonation(userProcessContainer, userAccount);
        userProcessContainer.add("manageCityJPanel", manageCityJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnBestCitizenActionPerformed

    private void btnFoodCollectedCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodCollectedCitizenActionPerformed
        // TODO add your handling code here:
        TypeOfFoodCitizens manageCityJPanel = new TypeOfFoodCitizens(userProcessContainer, userAccount);
        userProcessContainer.add("manageCityJPanel", manageCityJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFoodCollectedCitizenActionPerformed

    private void btnFoodCollectedRestaurqantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodCollectedRestaurqantActionPerformed
        // TODO add your handling code here:
        TypesOfFoodRestaurant manageCityJPanel = new TypesOfFoodRestaurant(userProcessContainer, userAccount);
        userProcessContainer.add("manageCityJPanel", manageCityJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnFoodCollectedRestaurqantActionPerformed

    private void btnMostPopularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostPopularAreaActionPerformed
        // TODO add your handling code here:
        MostPopularLocation manageCityJPanel = new MostPopularLocation(userProcessContainer, userAccount);
        userProcessContainer.add("manageCityJPanel", manageCityJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMostPopularAreaActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBestCitizen;
    private javax.swing.JButton btnFoodCollectedCitizen;
    private javax.swing.JButton btnFoodCollectedRestaurqant;
    private javax.swing.JButton btnMostPopularArea;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
