/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.FoodCollectionSupervisor;

import Business.Community.Community;
import Business.Employee.FoodCollectionSupervisorEmployee;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodCollectionWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author gauripatil
 */
public class TotalFoodDonation extends javax.swing.JPanel {

    /**
     * Creates new form TotalFoodDonation
     */
      private JPanel userProcessContainer;
    private UserAccount account;
    private Community community;
    private Organization organization;
    public TotalFoodDonation(JPanel userProcessContainer,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        FoodCollectionSupervisorEmployee empSupervisor =  (FoodCollectionSupervisorEmployee) account.getEmployee();
        community = empSupervisor.getCommunityAssociated();
        organization =  community.getFoodCollectionOrganization();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(25, 118, 242));
        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total types Food donated");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 190, -1));

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 190, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From Date :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To Date :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, 29));

        btnCalculate.setBackground(new java.awt.Color(25, 118, 242));
        btnCalculate.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("RUN");
        btnCalculate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 90, 40));

        btnBack1.setBackground(new java.awt.Color(25, 118, 242));
        btnBack1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("BACK");
        btnBack1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 370, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        
        Date toDate1=jDateChooser1.getDate();
        Date toDate2=jDateChooser2.getDate();
        if ((toDate1==null) || (toDate2==null)){
            JOptionPane.showMessageDialog(null, "Invalid date..Kindly enter valid date.");
            return;         
        }
        long fromDate = (jDateChooser1.getDate().getTime())/(1000*60*60*24);
        long toDate =  (jDateChooser2.getDate().getTime())/(1000*60*60*24);
        int homeFoodType = 0;
        int cannedType = 0;
        int purchasedType = 0;
        
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestArrayList()){
                 
          long requestDate =  (request.getRequestDate().getTime())/(1000*60*60*24);
          
             if ((requestDate>=fromDate) && (requestDate <= toDate) ){
               if (!request.getStatus().equalsIgnoreCase("New Request")){
                    if(((FoodCollectionWorkRequest) request).getFood().getFoodType().equalsIgnoreCase("Canned Food")){
                        cannedType++;
                    }
                    else if(((FoodCollectionWorkRequest) request).getFood().getFoodType().equalsIgnoreCase("Home made Food")){
                        homeFoodType++;
                        
                    }
                    else if (((FoodCollectionWorkRequest) request).getFood().getFoodType().equalsIgnoreCase("Purchased Food")){
                        purchasedType++;
                    }
                }
             }
//             else{
//                 
//                 JOptionPane.showMessageDialog(null, "There are no records for this search criteria.");
//             }
//             
          
        }
        
             DefaultCategoryDataset dataset = new DefaultCategoryDataset();
             dataset.setValue(cannedType, "Number of food collected", "Canned Food");
             dataset.setValue(purchasedType, "Number of food collected", "Purchased Food");
             dataset.setValue(homeFoodType,  "Number of food collected", "Home made Food");
             
             JFreeChart chart = ChartFactory.createBarChart("Types of food collected", "Types of food", "Number of food collected", dataset, PlotOrientation.VERTICAL, false, true, false);
             CategoryPlot plot = chart.getCategoryPlot();
             plot.setRangeGridlinePaint(Color.BLUE);
             ChartFrame frame = new ChartFrame("Bar Chart for Types of food collected",chart);
             frame.setVisible(true);
             frame.setSize(450, 350);
            
        
    
         
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCalculate;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
