/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.FoodEnterpriseAdminWorkArea;

import Business.City.City;
import Business.Community.Community;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FoodManagementEnterprise;
import Interface.SystemAdminWorkArea.UpdateValue;
import java.awt.CardLayout;
import java.awt.Font;
import static java.time.Clock.system;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gauripatil
 */
public class ManageCommunity extends javax.swing.JPanel {

    /**
     * Creates new form ManageCommunity
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private FoodManagementEnterprise foodManagementEnterprise;
    public ManageCommunity(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        lblErrCommunity.setVisible(false);
        tblCommunity.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 18));
    }
    
    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblCommunity.getModel();
        model.setRowCount(0);
        if (enterprise instanceof FoodManagementEnterprise){
          FoodManagementEnterprise foodManagementEnterprise  =(FoodManagementEnterprise) enterprise;
          this.foodManagementEnterprise = foodManagementEnterprise;
             for(Community community: foodManagementEnterprise.getCommunityArrayList() ){
                 
                 Object[] row = new Object[1];
                 row[0]= community.getCommunityName();
                 model.addRow(row);
             }
        
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCommunity = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblErrCommunity = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        label1.setText("label1");

        setBackground(new java.awt.Color(25, 118, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCommunity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblCommunity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Community Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCommunity);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 117, 703, 136));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Community :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 354, -1, -1));

        txtCommunity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 351, 190, -1));

        btnSubmit.setBackground(new java.awt.Color(25, 118, 242));
        btnSubmit.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 180, 40));

        lblErrCommunity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrCommunity.setForeground(new java.awt.Color(255, 0, 51));
        lblErrCommunity.setText("errMessage");
        add(lblErrCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 354, -1, -1));

        btnBack.setBackground(new java.awt.Color(25, 118, 242));
        btnBack.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Community");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 18, -1, -1));

        jButton1.setBackground(new java.awt.Color(25, 118, 242));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete Community");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 220, 40));

        jButton3.setBackground(new java.awt.Color(25, 118, 242));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update Community");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 180, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCommunityActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String name = txtCommunity.getText();
        
        if(name.isEmpty() ){
            
            JOptionPane.showMessageDialog(null, "Community Name cannot be empty");
            return;
        }
        
        Pattern p = Pattern.compile("^[a-zA-Z \\s]+");
        Matcher m = p.matcher(name);  
        if(!m.matches())
        {
            txtCommunity.setText("");
            JOptionPane.showMessageDialog(null, "Invalid Community Name");
            
            return;
        }
        
        if (enterprise instanceof FoodManagementEnterprise){
            FoodManagementEnterprise foodManagementEnterprise  =(FoodManagementEnterprise) enterprise;
            if(null != foodManagementEnterprise.getCommunityArrayList() && !foodManagementEnterprise.getCommunityArrayList().isEmpty())
            {
                for(Community community : foodManagementEnterprise.getCommunityArrayList())
                {
                    if(name.equalsIgnoreCase(community.getCommunityName()))
                    {
                        txtCommunity.setText("");
                        JOptionPane.showMessageDialog(null, "Community Already exist");
            
                        return;
                    }
                }
            }
            foodManagementEnterprise.addCommunity(name);
            populateTable();
        }
        txtCommunity.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          int row = tblCommunity.getSelectedRow();
		if (row < 0)
		{
			JOptionPane.showMessageDialog(null, "Please select Community");
			return;
		}
		
		List<Community> tempCommunity = new ArrayList<>();
                DefaultTableModel model = (DefaultTableModel) tblCommunity.getModel();
		String communityname = model.getValueAt(row, 0).toString();

		FoodManagementEnterprise foodManagementEnterprise  =(FoodManagementEnterprise) enterprise;
                Community tempCommuity = null;
            if(null != foodManagementEnterprise.getCommunityArrayList() && !foodManagementEnterprise.getCommunityArrayList().isEmpty())
            {
                for(Community community : foodManagementEnterprise.getCommunityArrayList())
                {
                    if(communityname.equalsIgnoreCase(community.getCommunityName()))
                    {
                        tempCommuity = community;
                    }
		}
                foodManagementEnterprise.getCommunityArrayList().remove(tempCommuity);
		populateTable();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = tblCommunity.getSelectedRow();
		if (row < 0)
		{
			JOptionPane.showMessageDialog(null, "Please select community");
			return;
		}
		
		Community tempCommunity = null;

                DefaultTableModel model = (DefaultTableModel) tblCommunity.getModel();
		String communityName = model.getValueAt(row, 0).toString();
                
		if (null != foodManagementEnterprise.getCommunityArrayList() && !foodManagementEnterprise.getCommunityArrayList().isEmpty())
		{
			for (Community community : foodManagementEnterprise.getCommunityArrayList())
			{
				if (communityName.equalsIgnoreCase(community.getCommunityName()))
				{
					tempCommunity = community;
					break;
				}
			}
		}

		new UpdateValue(tempCommunity,null,foodManagementEnterprise,this).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblErrCommunity;
    private javax.swing.JTable tblCommunity;
    private javax.swing.JTextField txtCommunity;
    // End of variables declaration//GEN-END:variables
}
